model = "gpt-5-codex"
model_reasoning_effort = "high"
approval_policy="on-failure"
sandbox_mode   = "workspace-write"
ask-for-approval="on-failure"
sandbox="danger-full-access"
windows_wsl_setup_acknowledged = true

[mcp_servers.Context7]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@upstash/context7-mcp", "--key", "4f09e527-a771-49c9-9a13-bb1984e763e8"]

[mcp_servers.server-sequential-thinking]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@smithery-ai/server-sequential-thinking", "--key", "4f09e527-a771-49c9-9a13-bb1984e763e8", "--profile", "raspy-bee-wGFRgg"]
disabled = false
autoApprove = []

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@microsoft/playwright-mcp", "--key", "4f09e527-a771-49c9-9a13-bb1984e763e8"]

[mcp_servers.desktop-commander]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@wonderwhy-er/desktop-commander", "--key", "4f09e527-a771-49c9-9a13-bb1984e763e8"]
startup_timeout_sec = 600
tool_timeout_sec = 600


[mcp_servers.railway-mcp]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@jason-tan-swe/railway-mcp", "--key", "4f09e527-a771-49c9-9a13-bb1984e763e8", "--profile", "pputty"]
startup_timeout_sec = 600
tool_timeout_sec = 600
# token = fe6e7460-bea0-4b02-a782-8a8e1a43a6e9


# [mcp_servers.linear]
# npx -y mcp-remote https://mcp.linear.app/sse
# command = "npx"
# args = ["-y", "mcp-remote", "https://mcp.linear.app/sse"]
# startup_timeout_sec = 600
# tool_timeout_sec    = 600
